address = "0.0.0.0:8000"
serve_dir = "../frontend/dist"

[openai]
disabled = true
endpoint = "https://api.openai.com/v1/chat/completions"
token = ""
rate_limit = 2

[google_gemini]
disabled = true
endpoint = ""
token = ""
rate_limit = 60
